### ISSUE TITLE
Intervene works well with 3-way lists, but not 2?

### ISSUE THREAD

**Issue by dayanne-castro** [asntech/intervene#1]
Hello,
I am having trouble running intervene with two files, but with 3 it works easily...

    a = open(options.a, 'r').read().splitlines()
AttributeError: 'Namespace' object has no attribute 'a'

Thanks,
D.

**Comment by asntech** [comment]
Thanks @dayanne-castro for reporting this. I've fixed it in the latest commit.

**Comment by asntech** [comment]
Update the intervene to the latest version v0.5.9 using;

`pip install intervene --upgrade`

OR

`conda update intervene`
