### ISSUE TITLE
Bed files

### ISSUE THREAD

**Issue by sarah872** [asntech/intervene#14]
Could you explain how you come up with the bedfiles/how do I generate them?

**Comment by asntech** [comment]
BED files stores genomic loci as chromosome name, its start, and end. The BED file format is described here in detail https://genome.ucsc.edu/FAQ/FAQformat.html#format1

**Comment by sarah872** [comment]
I was asking because I want to compare 2 (bacterial) species. Can intervene be used for that?

**Comment by asntech** [comment]
You can compare using Intervene if both species have the same names and number of chromosome(s).
