### ISSUE TITLE
pairwise function have problems on --names and --sort

### ISSUE THREAD

**Issue by clouds-drift** [asntech/intervene#15]
Sorry, the --names is fine.
But, it automatically sort the label by  name and I can't change the label order.
I'm using intervene version 0.6.4

cmd=paste("intervene pairwise -i", peak.file, "--output ../graph/Peak_without_control --filenames --compute frac --htype color --figsize 10 10 --project marker_pairwise_heatmap --diagonal", --names my.name, sep=""))

**Comment by asntech** [comment]
I have noticed that you have --filenames and then also using the --names. Can you try by the --filenames. Once --filenames is set then it ignores the --names.

**Comment by clouds-drift** [comment]
> I have noticed that you have --filenames and then also using the --names. Can you try by the --filenames. Once --filenames is set then it ignores the --names.
Yes, that's true and the --names and --filenames work well . I'm sorry for my title make some misunderstanding. 
But the --sort switch seems not working. Whatever --sort is, it always sort the provided names.

Thanks.

**Comment by asntech** [comment]
--sort just sorts the bed regions not the provided labels or filename. But, I will test it and check what is wrong. You only need to set the --sort if you compute jaccard or reldist. In your example, you don't the --sort since you're computing the fraction of overlap.

**Comment by clouds-drift** [comment]
Thank you for the explanation! I'm sorry for the misunderstanding of "--sort".
So it seems there's no parameter to switch off the order of  label name. It automatically order the provided label names.
