### ISSUE TITLE
Bedtools intersect error

### ISSUE THREAD

**Issue by jaqx008** [asntech/intervene#19]
Hello GitHub Users, I am running a shell script and during the run I get this error although the script goes on to finish but its not generating my intersect bed.
the portion of the script the error is coming from is 
```
bedtools intersect -wa -a TE.bed -b "$i".allMap.bed | \
		awk '{print $1":"$2"-"$3}' | sort | uniq -c | awk '$1 > 50' | \
		awk '{print $2"\t"$1}' > "$i"TEtargets.txt
		bedtools intersect -wa -a mRNA.bed -b "$i".allMap.bed | \
		awk '{print $1":"$2"-"$3}' | sort | uniq -c | awk '$1 > 50' | \
		awk '{print $2"\t"$1}' > "$i"mRNAtargets.txt
```

The Error is below

> ERROR: illegal character ' ' found in integer conversion of string "7  556442". Exiting...

**Comment by asntech** [comment]
Hi,
You need to file this issue here: https://github.com/arq5x/bedtools/issues

Thanks!
