### ISSUE TITLE
bedtools intersect options

### ISSUE THREAD

**Issue by adomingues** [asntech/intervene#3]
Feature suggestion as discussed via email with credits to @asntech .

It seems from looking at the source code that the genomic regions overlap is calculated using `pybedtools intersect` default settings which counts as intersection any regions that overlap by at least 1 bp. Could please consider 

1. adding a note to the Docs, and/or
2. consider adding an option to, for instance, consider an overlap only regions matching 100 %? The perfect solution would be to  an option, where user will be able to list any of the arguments available for bedtool’s intersect command. Something like this: --bedtool-options f=0.8,r=true,etc 

The default is perfectly sensible, but it might lead to unexpected results for those not aware of it.

**Comment by asntech** [comment]
Thanks @adomingues for the recomendation. Please try the latest release on GitHub now.

**Comment by asntech** [comment]
This option is now available in version v0.6.1 through _pip_
