### ISSUE TITLE
Error running intervene upset method

### ISSUE THREAD

**Issue by camilogarciabotero** [asntech/intervene#30]
Hi all,

Intervene is such a good program. Thank you letting it as open source.

On the other hand I was trying to run `intervene upset -i  /*gff` and got the following massages:

![Screen Shot 2020-02-27 at 10 21 11 AM](https://user-images.githubusercontent.com/25586362/75457781-e2751f80-594a-11ea-8bc8-418ecfb79cd2.png)

So, I was wondering if you can give some lights to solve this issue. By the way, I installed `intervene` via conda

Cheers,
Camilo

**Comment by asntech** [comment]
Sorry for the late response. Technically, it should install the UpSetR package. Did you try to install the UpSetR manually? Try this:
`conda install -c bioconda r-upsetr`

**Comment by camilogarciabotero** [comment]
Hi @asntech,

Yes. I did it and it worked great. Thank for the response. It could help others anyway!

Cheers.
