### ISSUE TITLE
update intervene's bedtools

### ISSUE THREAD

**Issue by mortunco** [asntech/intervene#33]
Hello,

I am having the exact issue below. When i update my bedtools, it solves the problem.

Is there a way to intagrate more updated version of the bedtools in intervene?

Thank you for developing and maintaining such an useful software. 

Best,

T.

https://github.com/arq5x/bedtools/issues/153

**Comment by Rohit-Satyam** [comment]
Hi! For me, conda version works fine with a little bit of version warning for matplotlib. Create a new environment in conda and install intervene using the command `conda install -c bioconda intervene`. This way you will not require to install bedtools separately.

Hope this helps!!
Cheers!!

**Comment by asntech** [comment]
I've updated the conda recipe and set `bedtools >=2.29.1`. This would fix this. Thanks!
