### ISSUE TITLE
AdobePiStd when loading UpSet PDFs in Illustrator

### ISSUE THREAD

**Issue by ilibarra** [asntech/intervene#36]
Dear Aziz,

Thank you for developing intervene.

When exporting PDFs and polishing them with Illustrator, I get this error. Because of this then circles in the matrix don't look ok.
https://stackoverflow.com/questions/9992275/ggplot2-pdf-import-in-adobe-illustrator-missing-font-adobepistd

Any chance of updating this to include this feature and avoid this problem while exporting plots? Alternative solutions are also welcome.

Thank you,
Ignacio

**Comment by asntech** [comment]
Thanks, Ignacio! This is fixed in the dev version 0.6.5.
