### ISSUE TITLE
Error using upset due to old version of UpSetR module in conda installation

### ISSUE THREAD

**Issue by nkschaefer** [asntech/intervene#38]
Hi,

I installed intervene using conda, but when running intervene upset, I ran into the following error:
```
Error in upset(fromExpression(expressionInput), nsets = 4, nintersects = 30,  : 
  unused arguments (mainbar.y.label = "No. of Intersections", sets.x.label = "Set size")
Execution halted
```
I checked, and the version of UpSetR that shipped with the conda installation was 1.3.0. I installed version 1.4.0 from source and it fixed this error. I think this dependency should be updated.

**Comment by mortunco** [comment]
I know its totally repeating the solution but might be useful for some people

stuff below fixed the error for me.
```
conda install -c conda-forge r-upsetr=1.4.0
```
