### ISSUE TITLE
Help running intervene?

### ISSUE THREAD

**Issue by jsanmig** [asntech/intervene#41]
Hello! I'm a novice user of python and condas, so please bear with me:

I was able to install intervene using condas and can see it in my environment using list:

conda list
# packages in environment at /anaconda3/envs/snakes:
#
# Name                    Version                   Build  Channel
bcftools                  1.8                  h4da6232_3    bioconda
bedops                    2.4.39               h770b8ee_0    bioconda
bedtools                  2.29.2               h37cfd92_0    bioconda
blas                      1.0                         mkl  
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2020.11.8            h033912b_0    conda-forge
certifi                   2018.8.24             py35_1001    conda-forge
curl                      7.61.1               ha441bb4_0  
cycler                    0.10.0           py35hb89929e_0  
freetype                  2.10.4               ha233b18_0  
htslib                    1.7                           0    bioconda
intel-openmp              2019.4                      233  
intervene                 0.5.8                    py35_0    bioconda
kiwisolver                1.0.1            py35h219a9d8_0  
libcurl                   7.61.1               hf30b1f0_0  
libcxx                    10.0.0                        1  
libdeflate                1.2                  h01d97ff_1    bioconda
libedit                   3.1.20191231         h1de35cc_1  
libffi                    3.2.1             h0a44026_1007  
libgfortran               3.0.1                h93005f0_2  
libpng                    1.6.37               ha441bb4_0  
libssh2                   1.8.0                h322a93b_4  
matplotlib                3.0.0            py35h54f8f79_0  
mkl                       2018.0.3                      1  
mkl_fft                   1.0.6            py35hb8a8100_0  
mkl_random                1.0.1            py35h5d10147_1  
ncurses                   6.2                  h0a44026_1  
numpy                     1.15.2           py35h6a91979_0  
numpy-base                1.15.2           py35h8a80b8c_0  
openssl                   1.0.2u               h0b31af3_0    conda-forge
pandas                    0.23.4           py35h6440ff4_0  
patsy                     0.5.0                    py35_0  
pip                       10.0.1                   py35_0  
pybedtools                0.8.0            py35ha92aebf_0    bioconda
pyparsing                 2.4.7                      py_0  
pysam                     0.14.1           py35hae42fb6_1    bioconda
python                    3.5.6                hc167b69_0  
python-dateutil           2.8.1                      py_0  
pytz                      2020.1                     py_0  
readline                  7.0                  h1de35cc_5  
samtools                  1.7                           1    bioconda
scipy                     1.1.0            py35h28f7352_1  
seaborn                   0.9.0              pyh91ea838_1  
setuptools                40.2.0                   py35_0  
six                       1.15.0                     py_0  
sqlite                    3.33.0               hffcf06c_0  
statsmodels               0.9.0            py35h917ab60_0  
tbb                       2020.3               h879752b_0  
tbb4py                    2018.0.5         py35h04f5b5a_0  
tk                        8.6.10               hb0a8c7a_0  
tornado                   5.1.1            py35h1de35cc_0  
wheel                     0.35.1                     py_0  
xz                        5.2.5                h1de35cc_0  
zlib                      1.2.11               h1de35cc_3  

However, when I try to run $intervene --help or $intervene I get the following message:
Traceback (most recent call last):
  File "/anaconda3/envs/snakes/bin/intervene", line 4, in <module>
    __import__('pkg_resources').run_script('intervene==0.5.8', 'intervene')
  File "/anaconda3/envs/snakes/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3105, in <module>
    @_call_aside
  File "/anaconda3/envs/snakes/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3089, in _call_aside
    f(*args, **kwargs)
  File "/anaconda3/envs/snakes/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3118, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/anaconda3/envs/snakes/lib/python3.5/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/anaconda3/envs/snakes/lib/python3.5/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/anaconda3/envs/snakes/lib/python3.5/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'intervene==0.5.8' distribution was not found and is required by the application

If I try to run bedtools for example, I have no issues.

Has it not installed properly? Am I missing something? Any help would be greatly appreciated. Thanks so much!!

**Comment by asntech** [comment]
It seems you installed an older version. Please try this:
`conda install -c bioconda intervene=0.6.4`

**Comment by jsanmig** [comment]
Hi!! I think not specifying the version on my first go-round had messed everything up! I made a new environment and was able to get intervene to install using 0.6.4.  Thank you so much!
