### ISSUE TITLE
total number diff in venn plot

### ISSUE THREAD

**Issue by whiteorchid** [asntech/intervene#46]
```
intervene venn -i ./*.bed --output .  --bedtools-options  f=1,s,r --figtype png --title "precision(100%)" 
mv Intervene_venn.png  compare_1.png
sleep 3 

intervene venn -i ./*.bed --output .  --bedtools-options  f=0.75,s,r --figtype png --title "precision(75%)"  
mv Intervene_venn.png  compare_0.75.png
sleep 3 

intervene venn -i ./*.bed --output .  --bedtools-options  f=0.5,s,r  --figtype png --title "precision(50%)"  
mv Intervene_venn.png  compare_0.5.png
sleep 3 

intervene venn -i ./*.bed --output .  --bedtools-options  f=0.25,s,r  --figtype png --title "precision(25%)" 
mv Intervene_venn.png  compare_0.25.png
sleep 3 

intervene venn -i ./*.bed --output .  --bedtools-options  f=0.1,s,r  --figtype png --title "precision(10%)"  
mv Intervene_venn.png  compare_0.1.png
sleep 3 
```
Hi dear author,

I have three bed files for intervene to draw the venn plot,  using the various fraction (0.1, 0.25, 0.5, 0.75, 1); and manually add the total numbers in the venn plot for each bed file, while A, B total number almost the same under fraction 0.1 and 1, the C bed file total number added from the venn plot has near 3000 difference (f=1 vs f=0.1); is this normal, how to adjust it? 

Thank you so  much!

**Comment by jiepan1** [comment]
Hi ,
I have the same problem. Have you solved it

**Comment by asntech** [comment]
Please check this issue https://github.com/asntech/intervene/issues/27
