### ISSUE TITLE
Intervene venn –save-overlaps not working

### ISSUE THREAD

**Issue by jharrison0123** [asntech/intervene#49]
Hi,

Running the command `intervene venn -I  <bed files> --names=<>` generated a Venn diagram but when I add --save-overlaps to get the intersections I get an error regardless if I do the default (False) or True to get the intersections.

intervene venn -I  <bed files> --names=<> --save-overlaps False
usage: intervene <subcommand> [options]
intervene: error: unrecognized arguments: False

intervene venn -I  <bed files> --names=<> --save-overlaps True
usage: intervene <subcommand> [options]
intervene: error: unrecognized arguments: True

**Comment by asntech** [comment]
The `--save-overlaps` argument does not require a parameter. By simply adding `--save-overlaps` without `True` or `False` will work.

**Comment by JHarrison0214** [comment]
Hi Aziz,

Thank you for your quick reply. When I only have the —save-overlaps argument, it only generates a folder with a .pdf of the Venn diagram.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by asntech** [comment]
What version you're using? And can you try `upset` with `intervene upset -i *.bed --save-overlaps`

**Comment by JHarrison0214** [comment]
I am using intervene version 0.6.5. I was getting an error because I did "-save-overlaps" instead of "--save-overlaps". Thank you for your help! It is a very helpful tool.

Jessica

**Comment by asntech** [comment]
That's great you figured it out, Jessica!

Cheers!
