### ISSUE TITLE
Unable to install using conda

### ISSUE THREAD

**Issue by kyleLesack** [asntech/intervene#50]
Hello. I am trying to install Intervene using conda, but haven't had any luck so far. I have tried some of the recommendations mentioned in some of the other issues, but they haven't worked either.

I tried forcing conda to install version 0.6.5: 

```
conda create -n intervene  intervene=0.6.5 -c bioconda
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                     

UnsatisfiableError: 

```
That's the full error message by the way. Nothing is printed after UnsatisfiableError.

I also tried specifying the Python version:

```
conda create -n intervene python=3.6 intervene=0.6.5 -c bioconda
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                     

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
python=3.6
intervene=0.6.5 -> matplotlib-base[version='<3.4'] -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0|>=3.7.1,<3.8.0a0|3.4.*|>=3.6']
intervene=0.6.5 -> pythonThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31
```

I also tried using mamba, but it can't find the needed version of upsetr:

```
mamba create -n intervene intervene=0.6.5 -c bioconda
 
Looking for: ['python=3.6', 'intervene=0.6.5']

bioconda/linux-64                                           Using cache
bioconda/noarch                                             Using cache
pkgs/r/noarch                                                 No change
pkgs/main/noarch                                              No change
pkgs/main/linux-64                                            No change
pkgs/r/linux-64                                               No change
Encountered problems while solving:
  - nothing provides r-upsetr >=1.4.0 needed by intervene-0.6.5-pyh3252c3a_0
```

I would appreciate any help. Thanks in advance!

**Comment by asntech** [comment]
@kyleLesack sorry for late reply. Did you fix this one if not can you please try this?

`R -e 'install.packages("UpSetR")'`

**Comment by kyleLesack** [comment]
Hello,

No need to apologize. No, I never got it working. 

I just created a new conda environment with R and ran the command you listed, but I still got the same errors as listed above when installing intervene.

Thanks for your help.

**Comment by asntech** [comment]
It seems the `bioconda` channel has an older version of  `r-upsetr`. You need to also add `conda-forge` to the channels. 

Try this:
`conda create -n intervene -c bioconda -c conda-forge -c defaults intervene=0.6.5`
OR
`mamba install -c bioconda -c conda-forge -c defaults intervene=0.6.5`

**Comment by asntech** [comment]
Just in case - I also added a Docker container for intervene #52

**Comment by kyleLesack** [comment]
> It seems the `bioconda` channel has an older version of `r-upsetr`. You need to also add `conda-forge` to the channels.
> 
> Try this: `conda create -n intervene -c bioconda -c conda-forge -c defaults intervene=0.6.5` OR `mamba install -c bioconda -c conda-forge -c defaults intervene=0.6.5`

I just tried the conda command and it worked. Thanks!
