### ISSUE TITLE
ipython-notebook not installing in conda

### ISSUE THREAD

**Issue by Folu0909** [asntech/intervene#51]
Dear all, would you kindly advise on how to go about this. Thanks

(base) C:\Users\Admin>conda install -c free ipython-notebook
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort./
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - ipython-notebook -> python[version='2.6.*|2.7.*|3.4.*|3.5.*|3.3.*']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

**Comment by asntech** [comment]
@Folu0909 please try this instead.
`conda install -c anaconda jupyter`

**Comment by asntech** [comment]
closing this as it is not related to Intervene - please reply if you've issues getting jupyter notebook running.

**Comment by Folu0909** [comment]
Thank you. It worked


Folu Paul-Odeniran, Ph.D. (she/her)

School of PharmacyUniversity of NottinghamA12, Biodiscovery Institute
University Park
Nottingham, NG7 2RD

+447776365577

**Comment by asntech** [comment]
Wonderful!!
