### ISSUE TITLE
--bedtools-options not available anymore?

### ISSUE THREAD

**Issue by sathvik-samaga** [asntech/intervene#63]
The documentation says the --bedtools-options can be used but I get an error message saying "intervene: error: unrecognized arguments: --bedtools-options f=0.3" . I am also not able to see the option when I type in 
```shell
intervene venn --help
```

**Comment by asntech** [comment]
@sathvik-samaga can you please make sure the version you're using `intervene --version`?

**Comment by sathvik-samaga** [comment]
@asntech you are right, I'm sorry I was somehow using version 0.6.0, I will update to the latest version now. Thank you for the help!
