### ISSUE TITLE
label size modification

### ISSUE THREAD

**Issue by asylvz** [asntech/intervene#64]
Thank you for the great tool. 

I want to increase the mblabel, sxlabel and intersection size label fonts; is this possible in the command line? I can do this from the shiny app, however, I cannot change the text of "Intersection size" and "Set size" there or upload mine with the plot.

Arda

**Comment by asntech** [comment]
@asylvz thanks for your interest and glad you liked the tool.

It is possible to do it also from the CLI. You can set the `--mblabel` and `--sxlabel` arguments. 

For example:
```
intervene upset -i path/to/BED/files/*.bed --mblabel "Your custom label" --sxlabel "Your custom label"
```

Hope this helps!

Aziz

**Comment by asylvz** [comment]
Thank you for your quick response @asntech. I mean I can do it from the command line, but I cannot increase the font size; on the other hand, if I use the shiny app, I can increase the font size, but I cannot change the label.

However, I solved it by modifying the R script and running from there; now it's fine.

Best
