### ISSUE TITLE
Install intervene latest version from conda

### ISSUE THREAD

**Issue by Phillip-a-richmond** [asntech/intervene#9]
Hey Aziz,
I'm trying to install intervene from bioconda cloud, and I'm having issues with getting the latest version. I even started a new miniconda2 from scratch, and I'm still getting the error:

conda install -c bioconda intervene=0.6.4
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - intervene=0.6.4
Use "conda info <package>" to see the dependencies for each package.

When I type:
conda install -c bioconda intervene
it works fine, but only gets me version 0.5.8

Any ideas on how to fix this? Or can I more explicitly refer to a specific version of intervene?

Cheers,
Phil

**Comment by hdingwall** [comment]
Hi Aziz,

Just wanted to add that I'm also getting this error.

Thanks!

**Comment by asntech** [comment]
Hi @hdingwall can you please try to install it using pip, which worked for @Phillip-a-richmond.
I'll look into this issue soon. Thanks!
